'use strict';
// Business rules adapted from the exact server(2).js supplied by the user.
// Calculation functions remain unchanged; no startup recalc of history is run.
const {readBody} = require('./transport');
const defaults={
  coffee_rural_fund:.0163,coffee_clean_bag_weight:60.2,coffee_coco_base_weight:41,coffee_moisture_limit:13,
  cacao_rural_fund:.0163,cacao_unit_weight:50.2,cacao_fixed_discount:0.2,cacao_moisture_limit:9,cacao_mold_discount:.05,cacao_brocade_discount:.20,
  nuts_rural_fund:.0163,nuts_unit_weight:50.2,nuts_fixed_discount:0.5,nuts_moisture_limit:0,
  deposit_months:6
};

function createLegacyContext(sourceDb, sourceAudit, currentUser) {
  const db=structuredClone(sourceDb);
  let auditDb=structuredClone(sourceAudit || {batches:[],items:[],logs:[]});
  let dirtyMain=false, dirtyAudit=false;
  db.settings={...defaults,...(db.settings||{})};
  function save(){dirtyMain=true;}
  function user(){return currentUser;}
  function body(req){return readBody(req);}
  function loadAuditDb(){return structuredClone(auditDb);}
  function saveAuditDb(a){auditDb=structuredClone(a);dirtyAudit=true;}
const trunc2=n=>Math.trunc((Number(n)||0)*100)/100;
const RURAL_FUND_CHANGE_DATE='2026-07-03',RURAL_FUND_PREVIOUS=.015;
function ruralRateForDate(dateStr,product){const current=product==='CACAU'?db.settings.cacao_rural_fund:product==='CASTANHAS'?db.settings.nuts_rural_fund:db.settings.coffee_rural_fund;return String(dateStr||'')<RURAL_FUND_CHANGE_DATE?RURAL_FUND_PREVIOUS:current}
function json(res,status,data){const b=Buffer.from(JSON.stringify(data));res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Content-Length':b.length,'Cache-Control':'no-store'});res.end(b)}
function addMonths(dateStr,n){const d=new Date(dateStr+'T12:00:00');d.setMonth(d.getMonth()+Number(n||6));return d.toISOString().slice(0,10)}
function isPurchase(op){return /^Compra/.test(op)}
function isDeposit(op){return op==='Depósito'}
function isStoredMovement(op){return ['Compra do Café Depositado','Compra do Cacau Depositado','Compra da Castanha Depositada','Retirada do Depósito','Ajuste de Entrada','Ajuste de Saída'].includes(op)}
function calcStoredMovement(i){const weight=trunc2(Math.max(0,+i.gross_weight||0)),price=+i.price||0,purchase=isPurchase(i.operation),rate=ruralRateForDate(i.date,i.product);let units=i.product==='CAFÉ'?trunc2(weight/db.settings.coffee_clean_bag_weight):i.product==='CASTANHAS'?Math.ceil(weight/db.settings.nuts_unit_weight):0;const gv=purchase?trunc2((i.product==='CAFÉ'?units:weight)*price):0,rf=trunc2(gv*rate);return {units,fixed_discount:0,moisture_discount:0,powder_discount:0,impurity_discount:0,mold_discount:0,brocade_discount:0,operational_discount:0,total_discount:0,physical_net_weight:weight,equivalent_weight:weight,gross_value:gv,rural_fund:rf,net_value:trunc2(gv-rf),price_basis:i.product==='CAFÉ'?'saca':'kg',rural_rate:rate}}
function calcCoffee(i){const s=db.settings,gross=+i.gross_weight||0,moist=+i.moisture||0;const factor=moist<=s.coffee_moisture_limit?1:Math.max(0,1-(moist-s.coffee_moisture_limit)/100);const physicalNet=trunc2(gross*factor);let bags=0;if(i.subtype==='Limpo')bags=physicalNet/s.coffee_clean_bag_weight;else bags=(gross/s.coffee_coco_base_weight)*(+i.yield_value||0)/s.coffee_clean_bag_weight;bags=trunc2(bags);const eq=trunc2(bags*s.coffee_clean_bag_weight),price=+i.price||0,gv=isPurchase(i.operation)?trunc2(bags*price):0,rate=ruralRateForDate(i.date,'CAFÉ'),rf=trunc2(gv*rate);return {units:bags,fixed_discount:0,moisture_discount:trunc2(gross-physicalNet),physical_net_weight:physicalNet,equivalent_weight:eq,gross_value:gv,rural_fund:rf,net_value:trunc2(gv-rf),price_basis:'saca',rural_rate:rate}}
function calcCacao(i){const s=db.settings,gross=+i.gross_weight||0,moist=+i.moisture||0;const units=Math.ceil(gross/s.cacao_unit_weight)||0;const fixed=trunc2(units*s.cacao_fixed_discount);const moistureDisc=moist>s.cacao_moisture_limit?trunc2(((moist-s.cacao_moisture_limit)/100)*gross):0;const mold=Math.max(0,+i.mold||0),brocade=Math.max(0,+i.brocade||0);const moldDisc=trunc2(mold*s.cacao_mold_discount),brocadeDisc=trunc2(brocade*s.cacao_brocade_discount);const qualityDisc=trunc2(moldDisc+brocadeDisc);const net=trunc2(Math.max(0,gross-fixed-moistureDisc-qualityDisc));const price=+i.price||0,gv=isPurchase(i.operation)?trunc2(net*price):0,rate=ruralRateForDate(i.date,'CACAU'),rf=trunc2(gv*rate);return {units,fixed_discount:fixed,moisture_discount:moistureDisc,powder_discount:0,impurity_discount:0,mold_discount:moldDisc,brocade_discount:brocadeDisc,operational_discount:qualityDisc,total_discount:trunc2(fixed+moistureDisc+qualityDisc),physical_net_weight:net,equivalent_weight:net,gross_value:gv,rural_fund:rf,net_value:trunc2(gv-rf),price_basis:'kg',rural_rate:rate}}
function calcNuts(i){const s=db.settings,gross=+i.gross_weight||0,moist=Math.max(0,+i.moisture||0);const units=Math.ceil(gross/s.nuts_unit_weight)||0;const fixed=trunc2(units*s.nuts_fixed_discount);const moistureDisc=moist>s.nuts_moisture_limit?trunc2(((moist-s.nuts_moisture_limit)/100)*gross):0;const net=trunc2(Math.max(0,gross-fixed-moistureDisc));const price=+i.price||0,gv=isPurchase(i.operation)?trunc2(net*price):0,rate=ruralRateForDate(i.date,'CASTANHAS'),rf=trunc2(gv*rate);return {units,fixed_discount:fixed,moisture_discount:moistureDisc,powder_discount:0,impurity_discount:0,mold_discount:0,brocade_discount:0,operational_discount:0,total_discount:trunc2(fixed+moistureDisc),physical_net_weight:net,equivalent_weight:net,gross_value:gv,rural_fund:rf,net_value:trunc2(gv-rf),price_basis:'kg',rural_rate:rate}}
function calculate(i){const r=isStoredMovement(i.operation)?calcStoredMovement(i):(i.product==='CACAU'?calcCacao(i):i.product==='CASTANHAS'?calcNuts(i):calcCoffee(i));return {...r,expires_at:isDeposit(i.operation)?addMonths(i.date,db.settings.deposit_months):''}}
function balanceSign(op){return ['Depósito','Ajuste de Entrada'].includes(op)?1:['Compra do Café Depositado','Compra do Cacau Depositado','Compra da Castanha Depositada','Retirada do Depósito','Ajuste de Saída'].includes(op)?-1:0}
function dashboardFingerprint(t){return [String(t.cycle||'').trim(),String(t.product||'').trim(),String(t.date||'').trim(),Number(t.producer_id||0),String(t.operation||'').trim(),Number(t.gross_weight||0).toFixed(4),Number(t.equivalent_weight||0).toFixed(4),Number(t.price||0).toFixed(4)].join('|')}
function uniqueOperationalRows(rows){const seen=new Set();return rows.filter(t=>{const k=dashboardFingerprint(t);if(seen.has(k))return false;seen.add(k);return true})}
function balance(pid,cycle,product){return db.transactions.filter(t=>t.producer_id===pid&&t.product===product&&(!cycle||t.cycle===cycle)&&t.status!=='Cancelado').reduce((a,t)=>a+balanceSign(t.operation)*(+t.equivalent_weight||0),0)}
function joined(t){const p=db.producers.find(x=>x.id===t.producer_id)||{},u=db.users.find(x=>x.id===t.created_by)||{};return {...t,producer_name:p.name||'',producer_cpf:p.cpf||'',producer_city:p.city||'',producer_phone:p.phone||'',producer_code:p.code||p.id||'',user_name:u.name||''}}
function findProducerForAudit(r){const doc=String(r.cpf_cnpj||'').replace(/\D/g,'');let p=doc?db.producers.find(x=>String(x.cpf||'').replace(/\D/g,'')===doc):null;if(!p&&r.producer_name)p=db.producers.find(x=>String(x.name||'').trim().toUpperCase()===String(r.producer_name).trim().toUpperCase());return p}
function auditOperation(v){return /dep[oó]sito/i.test(String(v||''))?'Depósito':'Compra do Produtor'}
function auditTransactionData(r,b={}){const p=findProducerForAudit({...r,...b});return {date:b.date||r.tx_date||'',ticket:String(b.ticket??r.ticket??'').trim(),cycle:b.cycle||r.cycle||'',operation:b.operation||auditOperation(r.operation_expected||r.operation_source),product:'CACAU',producer_id:+(b.producer_id||(p&&p.id)||0),subtype:'',defects:0,yield_value:0,gross_weight:Number(b.gross_weight??r.gross_weight??0),moisture:Number(b.moisture??r.moisture??0),price:Number(b.price??r.price??0),mold:0,brocade:0,notes:b.notes??r.observation??'',manual_net_weight:Number(b.net_weight??r.net_weight??0),manual_gross_value:b.gross_value??r.gross_value,manual_rural_fund:b.rural_fund??r.rural_fund,manual_net_value:b.net_value??r.net_value}}
function applyManualValues(t,d,c){if(Number.isFinite(d.manual_net_weight)&&d.manual_net_weight>=0){t.physical_net_weight=trunc2(d.manual_net_weight);t.equivalent_weight=trunc2(d.manual_net_weight);t.total_discount=trunc2(Math.max(0,t.gross_weight-t.equivalent_weight))}if(d.manual_gross_value!==null&&d.manual_gross_value!==undefined)t.gross_value=trunc2(d.manual_gross_value);if(d.manual_rural_fund!==null&&d.manual_rural_fund!==undefined)t.rural_fund=trunc2(d.manual_rural_fund);if(d.manual_net_value!==null&&d.manual_net_value!==undefined)t.net_value=trunc2(d.manual_net_value);else if(d.manual_gross_value!==null&&d.manual_gross_value!==undefined)t.net_value=trunc2(t.gross_value-t.rural_fund);return t}
const handler=async(req,res)=>{try{const u=new URL(req.url,'http://localhost');
const me=user(req);if(!me)return json(res,401,{error:'Não autenticado'});if(req.method==='GET'&&u.pathname==='/api/me')return json(res,200,{user:{id:me.id,name:me.name,role:me.role}});
if(req.method==='GET'&&u.pathname==='/api/producers'){const q=(u.searchParams.get('q')||'').toLowerCase();const rows=db.producers.filter(p=>p.active!==false&&(!q||[p.name,p.cpf,p.city,p.code,p.phone,p.caf,p.car,p.idaron,p.uf,p.classification].some(v=>(v||'').toString().toLowerCase().includes(q)))).sort((a,b)=>(a.name||'').localeCompare(b.name||'','pt-BR'));return json(res,200,{rows:rows.slice(0,5000)})}
if(req.method==='POST'&&u.pathname==='/api/producers'){const b=await body(req);if(!b.cpf||!b.name)return json(res,400,{error:'CPF/CNPJ e nome são obrigatórios'});const doc=String(b.cpf).replace(/\D/g,'');if(doc.length!==11&&doc.length!==14)return json(res,400,{error:'Informe um CPF ou CNPJ válido'});if(db.producers.some(p=>String(p.cpf||'').replace(/\D/g,'')===doc&&p.active!==false))return json(res,409,{error:'CPF/CNPJ já cadastrado'});const p={id:db.seq.producer++,code:b.code||db.seq.producer-1,type:b.type||((doc.length===14)?'PJ':'PF'),cpf:b.cpf,name:b.name,city:b.city||'',uf:b.uf||'RO',phone:b.phone||'',caf:b.caf||'',car:b.car||'',idaron:b.idaron||'',classification:b.classification||'Produtor rural',address:b.address||'',notes:b.notes||'',active:true,created_by:me.id,created_at:new Date().toISOString()};db.producers.push(p);save();return json(res,201,{id:p.id})}
if(req.method==='PUT'&&/^\/api\/producers\/\d+$/.test(u.pathname)){const id=+u.pathname.split('/').pop(),p=db.producers.find(x=>x.id===id&&x.active!==false);if(!p)return json(res,404,{error:'Cadastro não encontrado'});const b=await body(req);if(!String(b.name||'').trim())return json(res,400,{error:'O nome é obrigatório'});const doc=String(b.cpf||'').replace(/\D/g,'');if(doc&&doc.length!==11&&doc.length!==14)return json(res,400,{error:'Informe um CPF ou CNPJ válido'});if(doc&&db.producers.some(x=>x.id!==id&&String(x.cpf||'').replace(/\D/g,'')===doc&&x.active!==false))return json(res,409,{error:'CPF/CNPJ já cadastrado em outro cadastro'});Object.assign(p,{code:String(b.code||p.code||id),type:b.type||p.type||((doc.length===14)?'PJ':'PF'),cpf:b.cpf||'',name:String(b.name).trim(),city:b.city||'',uf:(b.uf||'RO').toUpperCase(),phone:b.phone||'',caf:b.caf||'',car:b.car||'',idaron:b.idaron||'',classification:b.classification||p.classification||'Produtor rural',address:b.address||p.address||'',notes:b.notes||p.notes||'',updated_by:me.id,updated_at:new Date().toISOString()});save();return json(res,200,{ok:true,id:p.id})}
if(req.method==='GET'&&u.pathname==='/api/balance'){const pid=+u.searchParams.get('producer')||0,cycle=u.searchParams.get('cycle')||'',product=u.searchParams.get('product')||'';return json(res,200,{balance:trunc2(balance(pid,cycle,product))})}
if(req.method==='GET'&&u.pathname==='/api/deposits-summary'){const product=u.searchParams.get('product')||'',cycle=u.searchParams.get('cycle')||'',cpf=String(u.searchParams.get('cpf')||'').replace(/\D/g,''),pid=+u.searchParams.get('producer')||0;let rows=db.transactions.filter(t=>t.status!=='Cancelado'&&balanceSign(t.operation)!==0);if(product)rows=rows.filter(t=>t.product===product);if(cycle)rows=rows.filter(t=>t.cycle===cycle);if(pid)rows=rows.filter(t=>t.producer_id===pid);if(cpf)rows=rows.filter(t=>{const p=db.producers.find(x=>x.id===t.producer_id)||{};return String(p.cpf||'').replace(/\D/g,'').includes(cpf)});const groups=new Map();for(const t of rows){const k=[t.producer_id,t.product,t.cycle].join('|'),p=db.producers.find(x=>x.id===t.producer_id)||{};if(!groups.has(k))groups.set(k,{producer_id:t.producer_id,producer_name:p.name||'',producer_cpf:p.cpf||'',product:t.product,cycle:t.cycle,deposited:0,withdrawn:0,balance:0,movements:0});const g=groups.get(k),w=+t.equivalent_weight||0,sgn=balanceSign(t.operation);if(sgn>0)g.deposited+=w;else g.withdrawn+=w;g.balance+=sgn*w;g.movements++}const list=[...groups.values()].map(g=>({...g,deposited:trunc2(g.deposited),withdrawn:trunc2(g.withdrawn),balance:trunc2(g.balance)})).filter(g=>Math.abs(g.balance)>.001||g.deposited||g.withdrawn).sort((a,b)=>a.product.localeCompare(b.product)||String(a.cycle).localeCompare(String(b.cycle),undefined,{numeric:true})||a.producer_name.localeCompare(b.producer_name,'pt-BR'));const totals=list.reduce((a,g)=>({deposited:a.deposited+g.deposited,withdrawn:a.withdrawn+g.withdrawn,balance:a.balance+g.balance}),{deposited:0,withdrawn:0,balance:0});const cycles=[...new Set(db.transactions.filter(t=>balanceSign(t.operation)!==0&&(!product||t.product===product)).map(t=>t.cycle).filter(Boolean))].sort((a,b)=>b.localeCompare(a,undefined,{numeric:true}));return json(res,200,{rows:list,cycles,totals:{deposited:trunc2(totals.deposited),withdrawn:trunc2(totals.withdrawn),balance:trunc2(totals.balance)}})}
if(req.method==='POST'&&u.pathname==='/api/calculate')return json(res,200,calculate(await body(req)));
if(req.method==='GET'&&u.pathname==='/api/transactions'){let rows=db.transactions.slice();const pid=+u.searchParams.get('producer')||0,cycle=u.searchParams.get('cycle')||'',product=u.searchParams.get('product')||'';if(pid)rows=rows.filter(t=>t.producer_id===pid);if(cycle)rows=rows.filter(t=>t.cycle===cycle);if(product)rows=rows.filter(t=>t.product===product);rows.sort((a,b)=>(b.date+String(b.id).padStart(8,'0')).localeCompare(a.date+String(a.id).padStart(8,'0')));return json(res,200,{rows:rows.map(joined)})}
if(req.method==='GET'&&u.pathname.startsWith('/api/transactions/')){const id=+u.pathname.split('/').pop(),t=db.transactions.find(x=>x.id===id);if(!t)return json(res,404,{error:'Ticket não encontrado'});return json(res,200,{row:joined(t)})}
if(req.method==='POST'&&u.pathname==='/api/transactions'){const b=await body(req);if(!b.date||!b.cycle||!b.producer_id||!b.product||!['CAMILA','ADENILDA','VANESA'].includes(String(b.attendant||'').toUpperCase()))return json(res,400,{error:'Data, ciclo, produtor, produto e atendente são obrigatórios'});b.attendant=String(b.attendant).toUpperCase();const prefix=b.product==='CACAU'?'CAC':b.product==='CASTANHAS'?'CAS':'CAF',ticket=String(b.ticket||`${prefix}-${new Date().getFullYear()}-${String(db.seq.transaction).padStart(6,'0')}`);if(db.transactions.some(t=>t.ticket===ticket))return json(res,409,{error:'Número de ticket já utilizado'});const c=calculate(b);if(['Compra do Café Depositado','Compra do Cacau Depositado','Compra da Castanha Depositada','Retirada do Depósito','Ajuste de Saída'].includes(b.operation)&&c.equivalent_weight>balance(+b.producer_id,b.cycle,b.product)+.01)return json(res,400,{error:'Saldo depositado insuficiente'});const t={id:db.seq.transaction++,date:b.date,ticket,cycle:b.cycle,operation:b.operation,product:b.product,producer_id:+b.producer_id,subtype:b.subtype||'',defects:+b.defects||0,yield_value:+b.yield_value||0,gross_weight:+b.gross_weight||0,moisture:+b.moisture||0,price:+b.price||0,mold:+b.mold||0,brocade:+b.brocade||0,notes:b.notes||'',attendant:b.attendant,status:'OK',created_by:me.id,created_at:new Date().toISOString(),...c};db.transactions.push(t);save();return json(res,201,{id:t.id,ticket,...c})}
if(req.method==='PUT'&&/^\/api\/transactions\/\d+$/.test(u.pathname)){const id=+u.pathname.split('/').pop(),t=db.transactions.find(x=>x.id===id);if(!t)return json(res,404,{error:'Ticket não encontrado'});const b=await body(req);if(!b.date||!b.cycle||!b.producer_id||!b.product||!['CAMILA','ADENILDA','VANESA'].includes(String(b.attendant||'').toUpperCase()))return json(res,400,{error:'Data, ciclo, produtor, produto e atendente são obrigatórios'});b.attendant=String(b.attendant).toUpperCase();const ticket=String(b.ticket||t.ticket||'').trim();if(!ticket)return json(res,400,{error:'O número do ticket é obrigatório na edição'});if(db.transactions.some(x=>x.id!==id&&x.ticket===ticket))return json(res,409,{error:'Número de ticket já utilizado'});const c=calculate(b);if(['Compra do Café Depositado','Compra do Cacau Depositado','Compra da Castanha Depositada','Retirada do Depósito','Ajuste de Saída'].includes(b.operation)){const available=db.transactions.filter(x=>x.id!==id&&x.producer_id===+b.producer_id&&x.product===b.product&&(!b.cycle||x.cycle===b.cycle)&&x.status!=='Cancelado').reduce((a,x)=>a+balanceSign(x.operation)*(+x.equivalent_weight||0),0);if(c.equivalent_weight>available+.01)return json(res,400,{error:'Saldo depositado insuficiente para esta alteração'})}const before=JSON.parse(JSON.stringify(t));Object.assign(t,{date:b.date,ticket,cycle:b.cycle,operation:b.operation,product:b.product,producer_id:+b.producer_id,subtype:b.subtype||'',defects:+b.defects||0,yield_value:+b.yield_value||0,gross_weight:+b.gross_weight||0,moisture:+b.moisture||0,price:+b.price||0,mold:+b.mold||0,brocade:+b.brocade||0,notes:b.notes||'',attendant:b.attendant,updated_by:me.id,updated_at:new Date().toISOString()},c);const manualNet=Number(b.manual_net_weight),manualGross=Number(b.manual_gross_value),manualRural=Number(b.manual_rural_fund),manualNetValue=Number(b.manual_net_value);if(Number.isFinite(manualNet)&&b.manual_net_weight!==''&&b.manual_net_weight!==undefined){t.physical_net_weight=trunc2(manualNet);t.equivalent_weight=trunc2(manualNet);t.total_discount=trunc2(Math.max(0,t.gross_weight-manualNet))}if(Number.isFinite(manualGross)&&b.manual_gross_value!==''&&b.manual_gross_value!==undefined)t.gross_value=trunc2(manualGross);if(Number.isFinite(manualRural)&&b.manual_rural_fund!==''&&b.manual_rural_fund!==undefined)t.rural_fund=trunc2(manualRural);if(Number.isFinite(manualNetValue)&&b.manual_net_value!==''&&b.manual_net_value!==undefined)t.net_value=trunc2(manualNetValue);else t.net_value=trunc2(t.gross_value-t.rural_fund);db.audit_log=db.audit_log||[];db.audit_log.unshift({at:new Date().toISOString(),user_id:me.id,user_name:me.name,action:'EDITAR_TICKET',transaction_id:id,ticket_before:before.ticket,ticket_after:t.ticket,before,after:JSON.parse(JSON.stringify(t))});save();return json(res,200,{ok:true,id:t.id,ticket:t.ticket,row:joined(t)})}
if(req.method==='GET'&&u.pathname==='/api/audit'){let a=loadAuditDb();const cycle=u.searchParams.get('cycle')||'',status=u.searchParams.get('status')||'',q=(u.searchParams.get('q')||'').toLowerCase();let items=a.items||[];if(cycle)items=items.filter(x=>x.cycle===cycle);if(status)items=items.filter(x=>x.erp_match_status===status);if(q)items=items.filter(x=>[x.ticket,x.producer_name,x.cpf_cnpj,x.source_file].some(v=>String(v||'').toLowerCase().includes(q)));return json(res,200,{version:a.version,generated_at:a.generated_at,batches:a.batches||[],implementation:a.implementation||{},items:items.slice(0,3000),total:items.length})}
if(req.method==='POST'&&/^\/api\/audit\/\d+\/(apply|update)$/.test(u.pathname)){const parts=u.pathname.split('/'),aid=+parts[3],action=parts[4],b=await body(req),a=loadAuditDb(),r=(a.items||[]).find(x=>+x.id===aid);if(!r)return json(res,404,{error:'Registro de auditoria não encontrado'});const d=auditTransactionData(r,b);if(!d.date||!d.ticket||!d.cycle||!d.producer_id||d.gross_weight<=0)return json(res,400,{error:'Preencha data, ticket, lote, produtor e peso bruto antes de implantar'});let t=r.erp_transaction_id?db.transactions.find(x=>x.id===+r.erp_transaction_id):null;if(!t)t=db.transactions.find(x=>x.ticket===d.ticket&&x.cycle===d.cycle);if(action==='apply'&&!t&&db.transactions.some(x=>x.ticket===d.ticket))return json(res,409,{error:'Esse ticket já existe em outro lote. Revise antes de implantar.'});const before=t?JSON.parse(JSON.stringify(t)):null,c=calculate(d);if(t){Object.assign(t,{date:d.date,ticket:d.ticket,cycle:d.cycle,operation:d.operation,product:'CACAU',producer_id:d.producer_id,gross_weight:d.gross_weight,moisture:d.moisture,price:d.price,notes:d.notes,updated_by:me.id,updated_at:new Date().toISOString()},c);applyManualValues(t,d,c)}else{t={id:db.seq.transaction++,date:d.date,ticket:d.ticket,cycle:d.cycle,operation:d.operation,product:'CACAU',producer_id:d.producer_id,subtype:'',defects:0,yield_value:0,gross_weight:d.gross_weight,moisture:d.moisture,price:d.price,mold:0,brocade:0,notes:d.notes,status:'OK',created_by:me.id,created_at:new Date().toISOString(),...c};applyManualValues(t,d,c);db.transactions.push(t)}r.erp_transaction_id=t.id;r.erp_match_status='CONCILIADO';r.import_decision=before?'ATUALIZADO_PELO_USUARIO':'IMPLANTADO_PELO_USUARIO';r.tx_date=t.date;r.ticket=t.ticket;r.cycle=t.cycle;r.operation_expected=t.operation;r.gross_weight=t.gross_weight;r.net_weight=t.equivalent_weight;r.price=t.price;r.gross_value=t.gross_value;r.rural_fund=t.rural_fund;r.net_value=t.net_value;r.divergences=[];a.logs=a.logs||[];a.logs.unshift({at:new Date().toISOString(),user_id:me.id,user_name:me.name,audit_id:aid,transaction_id:t.id,action:before?'ATUALIZAR':'IMPLANTAR',before,after:t});save();saveAuditDb(a);return json(res,200,{ok:true,id:t.id,ticket:t.ticket,mode:before?'updated':'created'})}
if(req.method==='GET'&&/^\/api\/audit\/\d+$/.test(u.pathname)){const aid=+u.pathname.split('/').pop(),a=loadAuditDb(),r=(a.items||[]).find(x=>+x.id===aid);if(!r)return json(res,404,{error:'Registro de auditoria não encontrado'});const t=r.erp_transaction_id?db.transactions.find(x=>x.id===+r.erp_transaction_id):db.transactions.find(x=>x.ticket===r.ticket&&x.cycle===r.cycle);return json(res,200,{audit:r,erp:t?joined(t):null,producer:findProducerForAudit(r)||null})}
if(req.method==='GET'&&u.pathname==='/api/settings')return json(res,200,{settings:db.settings});
if(req.method==='PUT'&&u.pathname==='/api/settings'){if(me.role!=='admin')return json(res,403,{error:'Apenas o administrador pode alterar parâmetros'});const b=await body(req);for(const k of Object.keys(defaults))if(b[k]!==undefined&&b[k]!=='')db.settings[k]=Number(b[k]);save();return json(res,200,{ok:true})}
if(req.method==='GET'&&u.pathname==='/api/daily-summary'){const date=u.searchParams.get('date')||new Date().toISOString().slice(0,10),products=['CAFÉ','CACAU','CASTANHAS'],dayRows=uniqueOperationalRows(db.transactions.filter(t=>t.date===date&&t.status!=='Cancelado')),summaries=products.map(product=>{const rows=dayRows.filter(t=>t.product===product),purchases=rows.filter(t=>isPurchase(t.operation)),deposits=rows.filter(t=>isDeposit(t.operation)),sum=(arr,k)=>arr.reduce((a,t)=>a+(+t[k]||0),0),weight=sum(rows,'equivalent_weight');return {product,weight,purchases:sum(purchases,'equivalent_weight'),deposits:sum(deposits,'equivalent_weight'),tickets:rows.length,producers:new Set(rows.map(t=>t.producer_id)).size,net_value:sum(purchases,'net_value')}}),allProducers=new Set(dayRows.map(t=>t.producer_id)).size,total={weight:summaries.reduce((a,x)=>a+x.weight,0),tickets:dayRows.length,producers:allProducers,net_value:summaries.reduce((a,x)=>a+x.net_value,0)};return json(res,200,{date,products:summaries,total})}
if(req.method==='GET'&&u.pathname==='/api/dashboard'){const product=u.searchParams.get('product')||'CAFÉ',cycle=u.searchParams.get('cycle')||'',productRows=uniqueOperationalRows(db.transactions.filter(t=>t.product===product&&t.status!=='Cancelado')),cycles=[...new Set(productRows.map(t=>String(t.cycle||'').trim()).filter(Boolean))].sort((a,b)=>b.localeCompare(a,undefined,{numeric:true})),rows=cycle?productRows.filter(t=>String(t.cycle)===cycle):productRows,purchases=rows.filter(t=>isPurchase(t.operation)),deposits=rows.filter(t=>isDeposit(t.operation)),intakes=rows.filter(t=>['Compra do Produtor','Depósito','Ajuste de Entrada'].includes(t.operation));const sum=(arr,k)=>arr.reduce((a,t)=>a+(+t[k]||0),0),gross=sum(intakes,'gross_weight'),net=sum(intakes,'equivalent_weight'),purchasedWeight=sum(purchases,'equivalent_weight'),grossValue=sum(purchases,'gross_value'),balanceKg=rows.reduce((a,t)=>a+balanceSign(t.operation)*(+t.equivalent_weight||0),0),weightLoss=Math.max(0,gross-net),eff=gross?net/gross*100:0,avg=purchasedWeight?grossValue/purchasedWeight:0;return json(res,200,{product,cycle,cycles,gross_weight:trunc2(gross),gross_value:trunc2(grossValue),rural_fund:trunc2(sum(purchases,'rural_fund')),net_value:trunc2(sum(purchases,'net_value')),balance:trunc2(balanceKg),deposits:trunc2(sum(deposits,'equivalent_weight')),purchases:trunc2(purchasedWeight),tickets:rows.length,producers:new Set(rows.map(t=>t.producer_id)).size,weight_loss:trunc2(weightLoss),weight_efficiency:Math.round(eff*100)/100,average_price:trunc2(avg),recent:rows.slice().sort((a,b)=>(b.date+String(b.id)).localeCompare(a.date+String(a.id))).slice(0,6).map(joined)})}
if(req.method==='GET'&&u.pathname==='/api/operations-center'){const today=u.searchParams.get('date')||new Date().toISOString().slice(0,10),active=db.transactions.filter(t=>t.status!=='Cancelado'),day=active.filter(t=>t.date===today),products=['CAFÉ','CACAU','CASTANHAS'],segments=products.map(product=>{const r=day.filter(t=>t.product===product&&['Compra do Produtor','Depósito','Ajuste de Entrada'].includes(t.operation));return {product,weight:trunc2(r.reduce((a,t)=>a+(+t.equivalent_weight||0),0)),tickets:r.length,producers:new Set(r.map(t=>t.producer_id)).size}}),purchases=day.filter(t=>isPurchase(t.operation)),depositBalance=active.reduce((a,t)=>a+balanceSign(t.operation)*(+t.equivalent_weight||0),0),audit=loadAuditDb(),pendingAudit=(audit.items||[]).filter(i=>i.erp_match_status!=='CONCILIADO').length,expired=active.filter(t=>t.operation==='Depósito'&&t.expires_at&&t.expires_at<=today).length,negative=[];for(const p of db.producers){for(const product of products){const b=balance(p.id,'',product);if(b<-.01)negative.push({producer:p.name,product,balance:trunc2(b)})}}return json(res,200,{date:today,segments,financial:trunc2(purchases.reduce((a,t)=>a+(+t.net_value||0),0)),deposit_balance:trunc2(depositBalance),tickets:day.length,producers:new Set(day.map(t=>t.producer_id)).size,pending:{audit:pendingAudit,expired_deposits:expired,negative_balances:negative.length,total:pendingAudit+expired+negative.length},recent:day.slice().sort((a,b)=>String(b.id).localeCompare(String(a.id))).slice(0,8).map(joined)})}
if(req.method==='GET'&&u.pathname==='/api/lots'){const product=u.searchParams.get('product')||'',rows=uniqueOperationalRows(db.transactions.filter(t=>t.status!=='Cancelado'&&(!product||t.product===product))),groups=new Map();for(const t of rows){if(!t.cycle)continue;const k=t.product+'|'+t.cycle;if(!groups.has(k))groups.set(k,{product:t.product,cycle:t.cycle,gross:0,net:0,deposits:0,purchases:0,gross_value:0,rural_fund:0,net_value:0,tickets:0,producers:new Set(),first_date:t.date,last_date:t.date});const g=groups.get(k);if(['Compra do Produtor','Depósito','Ajuste de Entrada'].includes(t.operation)){g.gross+=+t.gross_weight||0;g.net+=+t.equivalent_weight||0}if(isDeposit(t.operation))g.deposits+=+t.equivalent_weight||0;if(isPurchase(t.operation)){g.purchases+=+t.equivalent_weight||0;g.gross_value+=+t.gross_value||0;g.rural_fund+=+t.rural_fund||0;g.net_value+=+t.net_value||0}g.tickets++;g.producers.add(t.producer_id);if(t.date<g.first_date)g.first_date=t.date;if(t.date>g.last_date)g.last_date=t.date}const list=[...groups.values()].map(g=>({product:g.product,cycle:g.cycle,gross:trunc2(g.gross),net:trunc2(g.net),deposits:trunc2(g.deposits),purchases:trunc2(g.purchases),gross_value:trunc2(g.gross_value),rural_fund:trunc2(g.rural_fund),net_value:trunc2(g.net_value),tickets:g.tickets,producers:g.producers.size,efficiency:g.gross?Math.round(g.net/g.gross*10000)/100:0,average_price:g.purchases?trunc2(g.gross_value/g.purchases):0,first_date:g.first_date,last_date:g.last_date,status:'EM OPERAÇÃO'})).sort((a,b)=>b.cycle.localeCompare(a.cycle,undefined,{numeric:true}));return json(res,200,{rows:list})}
if(req.method==='GET'&&u.pathname==='/api/global-search'){const q=(u.searchParams.get('q')||'').trim().toLowerCase();if(q.length<2)return json(res,200,{rows:[]});const qd=q.replace(/\D/g,''),out=[];for(const p of db.producers){if([p.name,p.cpf,p.code,p.city].some(v=>String(v||'').toLowerCase().includes(q))||(qd&&String(p.cpf||'').replace(/\D/g,'').includes(qd)))out.push({type:'PRODUTOR',id:p.id,title:p.name,subtitle:`Código ${p.code||p.id} • ${p.cpf||'sem CPF'} • ${p.city||''}`})}for(const t of db.transactions){if([t.ticket,t.cycle,t.product,t.operation,t.attendant].some(v=>String(v||'').toLowerCase().includes(q))){const j=joined(t);out.push({type:'TICKET',id:t.id,title:`Ticket ${t.ticket}`,subtitle:`${j.producer_name} • ${t.product} • ${t.cycle} • ${trunc2(t.equivalent_weight)} kg`})}}return json(res,200,{rows:out.slice(0,30)})}
if(req.method==='GET'&&/^\/api\/producer\/\d+\/summary$/.test(u.pathname)){const id=+u.pathname.split('/')[3],p=db.producers.find(x=>x.id===id);if(!p)return json(res,404,{error:'Produtor não encontrado'});const rows=db.transactions.filter(t=>t.producer_id===id&&t.status!=='Cancelado').sort((a,b)=>(b.date+String(b.id)).localeCompare(a.date+String(a.id))),purchases=rows.filter(t=>isPurchase(t.operation)),gross=purchases.reduce((a,t)=>a+(+t.gross_weight||0),0),net=purchases.reduce((a,t)=>a+(+t.equivalent_weight||0),0),value=purchases.reduce((a,t)=>a+(+t.net_value||0),0),avg=net?purchases.reduce((a,t)=>a+(+t.gross_value||0),0)/net:0,dep=rows.reduce((a,t)=>a+balanceSign(t.operation)*(+t.equivalent_weight||0),0);return json(res,200,{producer:p,summary:{gross:trunc2(gross),net:trunc2(net),value:trunc2(value),average_price:trunc2(avg),deposit_balance:trunc2(dep),tickets:rows.length,last_date:rows[0]?.date||'',last_cycle:rows[0]?.cycle||''},timeline:rows.slice(0,100).map(joined)})}
return json(res,404,{error:'Rota não encontrada'});
} catch (e) { console.error('Legacy API failed:', e.name); json(res,500,{error:'Erro interno. Nenhuma alteracao foi confirmada.'}); }};
  return {handler, getState:()=>({db,audit:auditDb,dirtyMain,dirtyAudit})};
}
module.exports={createLegacyContext, defaults};
